---
title: "Social ecology and epidemiology of arboviral diseases"
output: html_document
---

<h5>I am a bilingual infectious disease epidemiologist on a mission to improve the health outcomes of marginalized populations through applied public health and community engagement.</h5>

***

<h3>
The ecology, spread, and risk of invasive  *Aedes aegypti* in California
</h3>

<center> <h5>
__Socio-demographic drivers of *Ae. aegypti* abundance in Los Angeles, CA:__ 
</h5></center>    

 For the first chapter of my dissertation, I was the lead investigator on project in collaboration with the Greater Los Angeles County Vector Control District (GLACVCD), and ran a household survey of 163 participants in sociodemographically diverse communities in Los Angeles County (LA), CA. Our aim was to quantify sociodemographic disparities in the risk of local Zika and dengue outbreaks in California. We found that a decrease in income of approximately $20,000 was associated with a 30% increase in Ae. aegypti abundance at the household level, highlighting the need for community-specific vector control programs. At each household we administered a survey, which I wrote in Spanish and English, and collected data on household characteristics and human behaviors. I designed the study and carried out all fieldwork in LA with the help of 3 undergraduate researchers who I managed. I also conducted all statistical and spatial analysis on household data and Ae. aegypti abundance. The publication for this project is currently in its end-stages of editing and will be submitted to PLoS Neglected Tropical Diseases in late May 2019.

***  

<center> <h4>
__Heterogeneities in *Ae. aegypti* blood and sugar-feeding in Los Anegeles, CA:__  
</h4></center>   

For the second chapter of my dissertation, I developed a cheaper and more efficient assay to identify blood and sugar-feeding patterns in Ae. aegypti mosquitoes, identified bloodmeal sources of Ae. aegypti in LA, and determined disparities in human-Ae. Aegypti exposure and biting. The new method I developed to detect blood and sugar-feeding in Ae. aegypti modifies the gold-standard anthrone assay, which quantifies fructose, lipids, and glycogen in insects, and requires 1/3 of the time and 1/10 of the cost compared to the gold-standard. For this new protocol, I reduced and scaled the reagents required for the original assay to fit within 96-well microplates, which are used to read absorbance. To validate this new protocol, I tested it on two cohorts of lab mosquitoes with known feeding histories. This involved rearing and maintaining an Ae. aegypti colony, and designing a series of feeding regimes to expose to adult Ae. aegypti to. I am now usingthis assay in conjunction with a classification algorithm to classify the adult Ae. aegypti I collected from LA households as having never taken a bloodmeal, likely taken one bloodmeal, or likely taken multiple bloodmeals. 

***  

<center> <h4>
__Mapping past, present, and future climatic suitability of *Ae. aegypti* in the United States:__  
</h4></center>   


***  
<h3>
Zika and dengue epidemiology in Iquitos, Peru
</h3>

<center> <h5>
__Proyecto Dengue; data management in Iquitos, Peru:__  
</h5></center>   

As the survey and data manager for the Proyecto Dengue Program Project Grant (P01, PIs Dr. Tom Scott and Dr. Amy Morrison), I developed and managed surveys and data-collection efforts for a longitudinal cohort study with over 15,000 participants under surveillance for dengue and Zika virus infections in Iquitos, Peru. My main duties were programming the CommCare mobile application system used to administer surveys in the field, designing surveys, translating and streamlining surveys and standard operating procedures into Spanish, field-testing applications and survey protocols in Iquitos, and administering trainings in Spanish on using the CommCare data collection application and data management to Peruvian doctors and field technicians in Iquitos. To to ensure that the surveys and mobile application system were user-friendly for the field-technicians while also maintained the integrity of the data, I served as a liaison between and communicated heavily with field technicians, project managers, the CommCare database management team, and project scientists. Additionally, I developed an extensive knowledge of dengue and Zika epidemiology and a strong understanding of the socio-demographic determinants of both diseases. 

***  

<h3>
Climate change and heath equity in California, California Department of Public Health
</h3>

<center> <h5>
__Projected future heat-related mobidity and motality attributed to changes in ambient temperature and extreme heat and cold events in California:__  
</h5></center>   

